name: Docs

on:
  push:
    branches: [master]
  release:
    types: [published]

jobs:
  build:
    runs-on:  ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: dlang-community/setup-dlang@v1
      with:
        compiler: ldc-latest

    - name: Build docs
      run: dub build --build=docs

    - name: Set branch name
      uses: nelonoel/branch-name@v1.0.1

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs
        destination_dir: ./docs/${{ env.BRANCH_NAME }}
        enable_jekyll: true
