name: Docs

on:
  push:
    branches: [master]
  create:
    tags:
      - v*

jobs:
  build:
    runs-on:  ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: dlang-community/setup-dlang@v1
      with:
        compiler: ldc-latest

    - name: Build docs
      run: dub build --build=docs

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs
        destination_dir: ./docs/${{ github.ref_name }}
        enable_jekyll: true
